spring.application.name=empAssessment

spring.datasource.url=jdbc:postgresql://localhost:5432/Assessment
spring.datasource.username=postgres
spring.datasource.password=rrj
server.port = 2454

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false